security.jwt.token.secret-key: my-secret-key
api-key: 3E0JQcHUTBMhM7TjkWT8jhtQokGe7Sw0

spring:
  datasource:
    platform: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/backenddb
    username: backend
    password: [backend]
    initialization-mode: always
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update

  
